# Generated by Django 2.2.4 on 2021-11-12 19:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=255, verbose_name='Comuna')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=255, verbose_name='Provincia')),
                ('estado', models.BooleanField(default=True)),
                ('comunas', models.ManyToManyField(blank=True, to='main.Comuna', verbose_name='Comunas')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=255, verbose_name='Comuna')),
                ('descripcion', models.TextField(max_length=500)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
            },
        ),
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=32718, verbose_name='Ubicación de la Veterinaria')),
                ('estado', models.BooleanField(default=True)),
                ('comuna', models.ManyToManyField(blank=True, to='main.Comuna', verbose_name='Comuna/s donde se encuentra la Veterinaria')),
                ('servicios', models.ManyToManyField(blank=True, to='main.Servicio', verbose_name='Servicios')),
            ],
            options={
                'verbose_name': 'Veterinaria',
                'verbose_name_plural': 'Veterinarias',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('provincias', models.ManyToManyField(blank=True, to='main.Provincia', verbose_name='Provincias')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Animal')),
                ('fecha_nac', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('sexo', models.IntegerField(choices=[(1, 'Macho'), (2, 'Hembra')], default=1, verbose_name='Sexo')),
                ('tamanho', models.IntegerField(choices=[(1, 'Pequeño'), (2, 'Mediano'), (3, 'Grande')], default=1, verbose_name='Tamaño')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('foto_perfil', models.ImageField(null=True, upload_to='animal')),
                ('esterilizado', models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=1, verbose_name='Esterilizado')),
                ('fecha_lleg', models.DateField(blank=True, null=True, verbose_name='Fecha de LLegada')),
                ('estado', models.BooleanField(default=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Especie', verbose_name='Especie')),
                ('tratamiento', models.ManyToManyField(blank=True, to='main.Tratamiento', verbose_name='Instrumentos de Gestión')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
