# Generated by Django 2.2.4 on 2021-11-18 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='tratamiento',
            field=models.ManyToManyField(blank=True, to='main.Tratamiento', verbose_name='Tratamientos'),
        ),
        migrations.RemoveField(
            model_name='veterinaria',
            name='comuna',
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Comuna', verbose_name='Comuna donde se encuentra la Veterinaria'),
        ),
    ]
