# Generated by Django 2.2.4 on 2021-11-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211117_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='estado_animal',
            field=models.IntegerField(choices=[(1, 'Perdido'), (2, 'En Adopción')], default=1, verbose_name='Estado Animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento Estimada'),
        ),
    ]
