# Generated by Django 2.2.4 on 2021-11-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211122_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='telefono',
            field=models.CharField(max_length=11, null=True, verbose_name='Teléfono'),
        ),
    ]
