# Generated by Django 2.2.4 on 2021-12-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211124_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre y Apellido'),
        ),
    ]
