# Generated by Django 2.2.4 on 2021-12-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211208_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=255, verbose_name='Cuidados')),
                ('descripcion', models.TextField(max_length=500)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuidado',
                'verbose_name_plural': 'Cuidados',
            },
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='servicio',
            field=models.IntegerField(choices=[(1, 'Busco a mi Dueño'), (2, 'Busco a mi Mascota')], verbose_name='Servicio'),
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre y Apellido')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=11, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('mensaje', models.TextField(max_length=500, verbose_name='Déjenos un mensaje explicando su interés')),
                ('estado', models.BooleanField(default=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Animal', verbose_name='Mascotas disponibles')),
            ],
            options={
                'verbose_name': 'Adopcion',
                'verbose_name_plural': 'Adopciones',
            },
        ),
    ]
