# Generated by Django 2.2.4 on 2021-12-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211212_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='estado_animal',
            field=models.CharField(choices=[('Perdido', 'Perdido'), ('En Adopción', 'En Adopción')], max_length=50, verbose_name='Estado Animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='esterilizado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=50, verbose_name='Esterilizado'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default=1, max_length=50, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tamanho',
            field=models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default=1, max_length=50, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='servicio',
            field=models.CharField(choices=[('Busco a mi Dueño', 'Busco a mi Dueño'), ('Busco a mi Mascota', 'Busco a mi Mascota')], max_length=50, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=50, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tamanho',
            field=models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=50, verbose_name='Tamaño'),
        ),
    ]
