# Generated by Django 2.2.4 on 2021-12-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_veterinaria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
