# Generated by Django 2.2.4 on 2021-12-14 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20211214_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='adopcion',
            name='adoptante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Adoptante'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
