# Generated by Django 2.2.4 on 2021-12-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211214_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='microchip',
            field=models.BigIntegerField(null=True, verbose_name='Microchip'),
        ),
    ]
