# Generated by Django 2.2.4 on 2021-12-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='fecha_lleg',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_nac',
            field=models.DateField(),
        ),
    ]
