# Generated by Django 2.2.4 on 2021-12-19 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211219_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='telefono',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='microchip',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Microchip'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='telefono',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='veterinaria',
            name='telefono',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Teléfono'),
        ),
    ]
